FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/trumplin-server ./cmd/server

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /bin/trumplin-server /app/server
COPY migrations /app/migrations

EXPOSE 8080

CMD ["/app/server"]

